# Generated by Django 4.0.1 on 2023-11-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policycard', '0004_userneeds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNeeds',
        ),
    ]
