# Generated by Django 4.0.1 on 2023-11-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_history', '0005_survey_transcript'),
        ('policycard', '0005_delete_userneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycard',
            name='survey_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Survey_id', to='chat_history.survey'),
        ),
        migrations.AddField(
            model_name='policycard',
            name='transcript_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transcript_id', to='chat_history.transcript'),
        ),
    ]
