# Generated by Django 4.0.1 on 2023-12-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_updated',
            field=models.BooleanField(default=False),
        ),
    ]
