# Generated by Django 4.2.2 on 2023-09-13 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_history', '0002_remove_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_messages',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_response', models.TextField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='chat_messages',
            name='transcript_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_history.transcript'),
        ),
    ]
