# Generated by Django 4.0.1 on 2023-11-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_history', '0004_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='transcript',
            field=models.ForeignKey(default='3db18a70-088c-4dd0-977f-b2a449209f95', on_delete=django.db.models.deletion.CASCADE, to='chat_history.transcript'),
            preserve_default=False,
        ),
    ]
