# Generated by Django 4.0.1 on 2023-11-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_history', '0005_survey_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
