# Generated by Django 4.0.1 on 2023-11-11 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('policycard', '0002_comment_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCard',
            fields=[
                ('eid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('downvote_count', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('userneed_id', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=255)),
                ('effective_date', models.DateTimeField()),
                ('policy_makers', models.CharField(max_length=255)),
                ('voting_status', models.BooleanField()),
                ('regional_info', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='policycard.policycard'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
